### PR TITLE
New icon

### PR DESCRIPTION
**Pull request by 20Koen02**
#14

### CODE REVIEW

**Review by devcer — DISMISSED** [review]

**Comment by devcer** [comment]
@20Koen02 This is approved. can you sign your commit so that I can merge this?

**Comment by devcer** [comment]
@20Koen02 This could provide better info about signing your commit -> https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/signing-commits

**Comment by devcer** [comment]
Since this is an existing commit. You can use this -> https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits

**Comment by 20Koen02** [comment]
fixed

**Review by devcer — APPROVED** [review]

**Pull request merged**
