### PR TITLE
created CONTRIBUTING.md in README.md as per #2

### PR DESCRIPTION
**Pull request by mohitsaha**
i have created how to contribute section and welcome section.

### CODE REVIEW

**Comment by mohitsaha** [comment]
should I have to add the contents of CONTRIBUTING.md in README.md?

**Comment by devcer** [comment]
Please go through the issue for a better understanding! https://github.com/devcer/hydrator/issues/2

**Comment by mohitsaha** [comment]
am i missing something?, i have changed the README.md and added "how to contribute" section.

**Comment by devcer** [comment]
The PR doesn't follow the instructions mentioned in the issue. closing this.

**Pull request closed without merging**
