### PR TITLE
Arranged some of the tags, added social link, correct grammatical errror

### PR DESCRIPTION
**Pull request by TechLead-21**

### CODE REVIEW

**Review by devcer — APPROVED** [review]

**Comment by devcer** [comment]
@TechLead-21 Looks good! Happy Hacktoberfest.

**Comment by TechLead-21** [comment]
Thank you bro :) can you plz add "hacktoberfest-accepted" label to this PR?

**Comment by devcer** [comment]
@TechLead-21 This is merged. The label is required only if I did not merge your changes but would accept it in near future.

**Comment by TechLead-21** [comment]
_Ok!! no problem_

**Pull request merged**
